### ISSUE TITLE
[Not Issue] Need Feedback Please

### ISSUE THREAD

**Issue by yousuf1997** [yousuf1997/TwitterHashtagAppProject#1]
Hi @siddeshpillai, 
 
 These are the followings thing I have done so far,
      
- Added Current Tweet and Favorite Tweet Database
- Card does not appear over the map like before
- When the user exists the app, and come back, previously searched tweets will appear on the list and also the name of it will be in the search textfields placeholder.
- Added Button to view current tweets, favorites tweets, and clear the tweets. If there is no tweet by default it will search "Esri" for tweets.
- When the user types on the search bar, and the top header will disappear, and when they enter or click the search button, it will appear back.

- Please visit this video for the demo I have created:
https://www.youtube.com/watch?v=cKJrsywhZC0&feature=youtu.be

Please let me know your opnion.

Thank you.

**Comment by siddeshpillai** [comment]
@yousuf1997 Good work. 

I'd suggest the twitter favorites experience can be streamlined even further. For e.g. watch the video to get inspiration on how to display button effects watch the button carefully. 

[twiiter.mov.zip](https://github.com/yousuf1997/TwitterHashtagAppProject/files/4976931/twiiter.mov.zip)

**Comment by siddeshpillai** [comment]
Can you make the transition from bottom to top instead of right to center for tweets?

**Comment by siddeshpillai** [comment]
<img width="422" alt="Screen Shot 2020-07-25 at 5 02 30 PM" src="https://user-images.githubusercontent.com/4101783/88468441-a366de00-ce98-11ea-8b31-fe04d88eff02.png">

Size of search bar is still large. Can you make it little smaller and add more contrast to suggestion text. I'd remove that tweet button on the right. It throws off the experience. You could simply say either go as text or add search icon. 

Make the width end to end for better presentation

**Comment by siddeshpillai** [comment]
You can move this to the top or anchor it to the bottom. 

Check how instagram display its menus in the bottom. 

![Uploading Screen Shot 2020-07-25 at 5.05.24 PM.png…]()

Avoid using text along with icon as button, it is against the design principles. Either use icon or text but not both.

**Comment by siddeshpillai** [comment]
Good effort overall. It is coming together well. Keep it up.

**Comment by yousuf1997** [comment]
Thank you for your feedback. I will look into it.

**Comment by yousuf1997** [comment]
Hi @siddeshpillai ,

               I have modified the card adding transition, and also changed the icons (removed the text). Please watch the video I attached. 
[transitionandicon.zip](https://github.com/yousuf1997/TwitterHashtagAppProject/files/4976997/transitionandicon.zip)

Thank You.

**Comment by yousuf1997** [comment]
Hi @siddeshpillai ,

                 I have attached the final design of the app, and also when ever the user clicks on the heart icon, the icon will zoom out litte and the icons color will change it red. Please refer the images.

Things I have done so far: 
       - The Users can share the link of the tweet by clicking the share buttom 
       - The App auto populates with the random coordinates within in the united states
       -  I have changed the pin icon, please refer the images
      - I have added the favorites, clear, and home buttons on the button.

![image](https://user-images.githubusercontent.com/28637938/88487791-0c079680-cf3d-11ea-833a-9313d35ea593.png)
![image](https://user-images.githubusercontent.com/28637938/88487796-16c22b80-cf3d-11ea-99f5-3eb0974c68e3.png)
